"""
Official constituent sets for Indian equity indices:
- NIFTY 50
- NIFTY 100
- NIFTY 500
- NIFTY MIDCAP 100
- NIFTY SMALLCAP 100
- NIFTY TOTAL MARKET
"""
from typing import Set, Dict, Optional

NIFTY_50_SYMBOLS: Set[str] = {'EICHERMOT', 'SBIN', 'LT', 'TATASTEEL', 'RELIANCE', 'TCS', 'KOTAKBANK', 'DRREDDY', 'MAXHEALTH', 'COALINDIA', 'BHARTIARTL', 'BEL', 'TMPV', 'JIOFIN', 'M&M', 'HDFCLIFE', 'SUNPHARMA', 'ASIANPAINT', 'ADANIENT', 'ICICIBANK', 'INFY', 'APOLLOHOSP', 'BAJAJFINSV', 'HDFCBANK', 'HCLTECH', 'SBILIFE', 'ADANIPORTS', 'POWERGRID', 'HINDUNILVR', 'AXISBANK', 'BAJAJ-AUTO', 'WIPRO', 'BAJFINANCE', 'GRASIM', 'NTPC', 'ETERNAL', 'SHRIRAMFIN', 'TITAN', 'ITC', 'TATACONSUM', 'TRENT', 'CIPLA', 'ULTRACEMCO', 'JSWSTEEL', 'NESTLEIND', 'HINDALCO', 'ONGC', 'MARUTI', 'TECHM', 'INDIGO'}
NIFTY_100_SYMBOLS: Set[str] = {'SBIN', 'IOC', 'MAXHEALTH', 'BHARTIARTL', 'HDFCAMC', 'MAZDOCK', 'SOLARINDS', 'TMPV', 'DIVISLAB', 'TATAPOWER', 'ASIANPAINT', 'DLF', 'ADANIENT', 'IRFC', 'ZYDUSLIFE', 'APOLLOHOSP', 'BOSCHLTD', 'HDFCBANK', 'HCLTECH', 'PIDILITIND', 'HINDUNILVR', 'BAJAJ-AUTO', 'BAJFINANCE', 'GRASIM', 'ETERNAL', 'SHRIRAMFIN', 'ITC', 'TRENT', 'ULTRACEMCO', 'UNIONBANK', 'SIEMENS', 'ONGC', 'ADANIGREEN', 'EICHERMOT', 'KOTAKBANK', 'ENRIN', 'LODHA', 'MOTHERSON', 'M&M', 'BAJAJHLDNG', 'HDFCLIFE', 'ICICIBANK', 'CUMMINSIND', 'RECLTD', 'WIPRO', 'SHREECEM', 'BRITANNIA', 'GODREJCP', 'TATACONSUM', 'MARUTI', 'TATACAP', 'RELIANCE', 'TCS', 'DMART', 'COALINDIA', 'PNB', 'HINDZINC', 'VBL', 'TMCV', 'INFY', 'AMBUJACEM', 'SBILIFE', 'ADANIPORTS', 'AXISBANK', 'NTPC', 'TITAN', 'CGPOWER', 'PFC', 'INDHOTEL', 'JSWSTEEL', 'GAIL', 'ADANIPOWER', 'TATASTEEL', 'LT', 'TVSMOTOR', 'DRREDDY', 'HAL', 'BEL', 'JIOFIN', 'TORNTPHARM', 'HYUNDAI', 'SUNPHARMA', 'VEDL', 'CANBK', 'LTM', 'BAJAJFINSV', 'UNITDSPR', 'POWERGRID', 'ABB', 'BANKBARODA', 'JINDALSTEL', 'MUTHOOTFIN', 'CIPLA', 'CHOLAFIN', 'BPCL', 'NESTLEIND', 'HINDALCO', 'TECHM', 'ADANIENSOL', 'INDIGO'}
NIFTY_500_SYMBOLS: Set[str] = {'HAVELLS', 'SBIN', 'TATACHEM', 'AARTIIND', 'IOC', 'M&MFIN', 'SOBHA', 'HOMEFIRST', 'BHARTIARTL', 'SOLARINDS', 'WHIRLPOOL', 'GMDCLTD', 'APTUS', 'ITI', 'DLF', 'IOB', 'NSLNISP', 'GALLANTT', 'UPL', 'AUBANK', 'AMBER', 'JUBLFOOD', 'OLECTRA', 'MEDANTA', 'OIL', 'TENNIND', 'OFSS', 'CEATLTD', 'LENSKART', 'SHRIRAMFIN', 'PNBHOUSING', 'ONGC', 'ADANIGREEN', 'CANFINHOME', 'BLUEDART', 'RITES', 'ATUL', 'NEWGEN', 'PTCIL', 'CUB', 'BLUESTARCO', 'HUDCO', 'NATIONALUM', 'AUROPHARMA', 'ACC', 'CEMPRO', 'CCL', 'NAM-INDIA', 'URBANCO', 'BSE', 'CUMMINSIND', 'TORNTPOWER', 'RECLTD', 'PPLPHARMA', 'INDIANB', 'NIACL', 'GLAXO', 'SIGNATURE', 'FIVESTAR', 'GICRE', 'ITCHOTELS', 'IGL', 'MRF', 'FACT', '3MINDIA', 'GODREJCP', 'NMDC', 'MEESHO', 'TARIL', 'HEROMOTOCO', 'TECHNOE', 'KEI', 'USHAMART', 'MSUMI', 'CREDITACC', 'ENGINERSIN', 'SBICARD', 'VBL', 'BAYERCROP', 'DALBHARAT', 'GMRAIRPORT', 'NH', 'GROWW', 'SBILIFE', 'SPLPETRO', 'TTML', 'LICHSGFIN', 'UCOBANK', 'MFSL', 'ABSLAMC', 'NCC', 'LUPIN', 'NTPC', 'LINDEINDIA', 'CHALET', 'MINDACORP', 'IFCI', 'ESCORTS', 'AEGISLOG', 'THELEELA', 'SJVN', 'EMMVEE', 'TATASTEEL', 'DRREDDY', 'HAL', 'SRF', 'ABDL', 'BEL', 'VMM', 'RPOWER', 'LATENTVIEW', 'HEXT', 'ACE', 'HYUNDAI', 'ARE&M', 'GVT&D', 'WELCORP', 'UNITDSPR', 'ZENSARTECH', 'ALKEM', 'CONCOR', 'J&KBANK', 'SUZLON', 'VTL', 'GLAND', 'KIMS', 'MANKIND', 'POWERGRID', 'ABB', 'EXIDEIND', 'UTIAMC', 'MANAPPURAM', 'AFCONS', 'CIPLA', 'MGL', 'BPCL', 'IIFL', 'SHYAMMETL', 'RVNL', 'INDIACEM', 'DEVYANI', 'GESHIP', 'MAXHEALTH', 'ANTHEM', 'GODFRYPHLP', 'SARDAEN', 'PAYTM', 'NAVINFLUOR', 'PERSISTENT', 'TATAPOWER', 'ADANIENT', 'PRESTIGE', 'BLS', 'IRB', 'BOSCHLTD', 'HDFCBANK', 'HCLTECH', 'PIDILITIND', 'INOXWIND', 'CARBORUNIV', 'BAJAJ-AUTO', 'ABCAPITAL', 'ASAHIINDIA', 'APLAPOLLO', 'ITC', 'POLYCAB', 'LALPATHLAB', 'TIMKEN', 'SIEMENS', 'IREDA', 'ZYDUSWELL', 'SWIGGY', 'DIXON', 'CENTRALBK', 'LODHA', 'SCHAEFFLER', 'SCI', 'FEDERALBNK', 'SAPPHIRE', 'ONESOURCE', 'JWL', 'BALRAMCHIN', 'ICICIBANK', 'SBFC', 'JSL', 'MMTC', 'INDIAMART', 'PWL', 'BALKRISIND', 'SUNDARMFIN', 'JINDALSAW', 'HDBFS', 'SUNTV', 'TATACONSUM', 'MRPL', 'CHAMBLFERT', 'RAMCOCEM', 'INTELLECT', 'TATACOMM', 'TATACAP', 'RELIANCE', 'GODREJIND', 'TCS', 'BHEL', 'IRCTC', '360ONE', 'WAAREEENER', 'PNB', 'ZENTEC', 'HONASA', 'GRANULES', 'APOLLOTYRE', 'KPITTECH', 'TMCV', 'PCBL', 'PFIZER', 'AMBUJACEM', 'MARICO', 'GODREJPROP', 'NTPCGREEN', 'DABUR', 'COLPAL', 'KPIL', 'GABRIEL', 'NAVA', 'HEGAM', 'PAGEIND', 'LTTS', 'IKS', 'DCMSHRIRAM', 'TVSMOTOR', 'HFCL', 'KAJARIACER', 'GLENMARK', 'CASTROLIND', 'IDBI', 'AAVAS', 'JKTYRE', 'IDFCFIRSTB', 'ICICIGI', 'OBEROIRLTY', 'FIRSTCRY', 'CROMPTON', 'AIIL', 'ATGL', 'HBLENGINE', 'DELHIVERY', 'LTFOODS', 'ECLERX', 'REDINGTON', 'RKFORGE', 'IRCON', 'TBOTEK', 'AIAENG', 'BANKBARODA', 'JINDALSTEL', 'CLEAN', 'SUMICHEM', 'CHOLAFIN', 'PREMIERENE', 'DEEPAKNTR', 'ADANIENSOL', 'INDIGO', 'TECHM', 'BIOCON', 'SAILIFE', 'HINDPETRO', 'HDFCAMC', 'ICICIAMC', 'POLYMED', 'TMPV', 'TEJASNET', 'DIVISLAB', 'EMCURE', 'IPCALAB', 'RBLBANK', 'FLUOROCHEM', 'JBMA', 'SAIL', 'ZYDUSLIFE', 'APOLLOHOSP', 'ENDURANCE', 'SWANCORP', 'KALYANKJIL', 'SCHNEIDER', 'MCX', 'HINDUNILVR', 'TRITURBINE', 'YESBANK', 'AFFLE', 'GRASIM', 'BLUEJET', 'ETERNAL', 'SONACOMS', 'TRENT', 'ULTRACEMCO', 'BERGEPAINT', 'FSL', 'BHARTIHEXA', 'EICHERMOT', 'BDL', 'GPIL', 'ENRIN', 'PATANJALI', 'COCHINSHIP', 'STARHEALTH', 'ELGIEQUIP', 'FORCEMOT', 'INDUSINDBK', 'M&M', 'HDFCLIFE', 'IGIL', 'LGEINDIA', 'NLCINDIA', 'GRSE', 'HINDCOPPER', 'NETWEB', 'JYOTICNC', 'EIDPARRY', 'CHENNPETRO', 'GRAVITA', 'CRAFTSMAN', 'ASTRAL', 'SHREECEM', 'BRITANNIA', 'KAYNES', 'CDSL', 'CIEINDIA', 'MARUTI', 'DOMS', 'JPPOWER', 'COHANCE', 'ACMESOLAR', 'PFOCUS', 'COROMANDEL', 'HINDZINC', 'SYNGENE', 'SYRMA', 'NAUKRI', 'VIJAYA', 'CESC', 'EMAMILTD', 'INDGN', 'AXISBANK', 'LEMONTREE', 'TITAGARH', 'TRIDENT', 'PFC', 'SAGILITY', 'JKCEMENT', 'POLICYBZR', 'BSOFT', 'ADANIPOWER', 'BBTC', 'TEGA', 'ANANTRAJ', 'ANANDRATHI', 'RRKABEL', 'SUPREMEIND', 'JIOFIN', 'JSWENERGY', 'PGEL', 'UBL', 'THERMAX', 'CRISIL', 'MPHASIS', 'VEDL', 'RAILTEL', 'LLOYDSME', 'LTM', 'BAJAJFINSV', 'APARINDS', 'HONAUT', 'ZEEL', 'GRAPHITE', 'KPRMILL', 'CANHLIFE', 'PIIND', 'VOLTAS', 'ANURAS', 'NIVABUPA', 'ASHOKLEY', 'ELECON', 'LICI', 'ASTERDM', 'BRIGADE', 'BANDHANBNK', 'MAZDOCK', 'NHPC', 'LTF', 'ASIANPAINT', 'IRFC', 'ZFCVINDIA', 'FINCABLES', 'ICICIPRULI', 'BIKAJI', 'SAMMAANCAP', 'ABLBL', 'CGCL', 'SONATSOFTW', 'JSWCEMENT', 'BAJFINANCE', 'UNOMINDA', 'POWERINDIA', 'UNIONBANK', 'DATAPATTNS', 'GODIGIT', 'ABBOTINDIA', 'BAJAJHFL', 'DEEPAKFERT', 'JAINREC', 'PARADEEP', 'KOTAKBANK', 'WOCKPHARMA', 'NATCOPHARM', 'CPPLUS', 'MOTHERSON', 'BAJAJHLDNG', 'PVRINOX', 'NEULANDLAB', 'NYKAA', 'RADICO', 'TATATECH', 'PIRAMALFIN', 'IDEA', 'RHIM', 'COFORGE', 'DUMMYHEG', 'TRAVELFOOD', 'WIPRO', 'MAPMYINDIA', 'ANGELONE', 'RAINBOW', 'CONCORDBIO', 'MOTILALOFS', 'CARTRADE', 'NUVOCO', 'KEC', 'TATAINVEST', 'DMART', 'POONAWALLA', 'CAMS', 'BANKINDIA', 'JSWINFRA', 'COALINDIA', 'ABFRL', 'MAHABANK', 'PHOENIXLTD', 'ACUTAAS', 'TATAELXSI', 'INFY', 'CAPLIPOINT', 'JUBLINGREA', 'ADANIPORTS', 'OLAELEC', 'BHARATFORG', 'BATAINDIA', 'EIHOTEL', 'HSCL', 'AJANTPHARM', 'AWL', 'CGPOWER', 'TITAN', 'ERIS', 'INDHOTEL', 'JSWSTEEL', 'SAREGAMA', 'GAIL', 'LT', 'ABREL', 'FORTIS', 'KARURVYSYA', 'NUVAMA', 'IEX', 'INDUSTOWER', 'TORNTPHARM', 'KIRLOSENG', 'JMFINANCIL', 'JUBLPHARMA', 'SUNPHARMA', 'JSWDULUX', 'KFINTECH', 'CANBK', 'CHOICEIN', 'WELSPUNLIV', 'AADHARHFC', 'BELRISE', 'AEGISVOPAK', 'NBCC', 'GILLETTE', 'PETRONET', 'PINELABS', 'CHOLAHLDNG', 'BEML', 'TIINDIA', 'MUTHOOTFIN', 'ATHERENERG', 'CYIENT', 'NESTLEIND', 'HINDALCO', 'LAURUSLABS'}
NIFTY_MIDCAP_100_SYMBOLS: Set[str] = {'HAVELLS', 'ASHOKLEY', 'BIOCON', 'GODFRYPHLP', 'M&MFIN', 'HINDPETRO', 'PAYTM', 'ICICIAMC', 'PERSISTENT', 'NHPC', 'LTF', 'PRESTIGE', 'SAIL', 'UPL', 'AUBANK', 'JUBLFOOD', 'KALYANKJIL', 'MCX', 'OIL', 'OFSS', 'ABCAPITAL', 'LENSKART', 'YESBANK', 'POWERINDIA', 'APLAPOLLO', 'POLYCAB', 'IREDA', 'BDL', 'SWIGGY', 'DIXON', 'PATANJALI', 'COCHINSHIP', 'BLUESTARCO', 'HUDCO', 'INDUSINDBK', 'FEDERALBNK', 'NATIONALUM', 'AUROPHARMA', 'NYKAA', 'LGEINDIA', 'RADICO', 'BSE', 'IDEA', 'COFORGE', 'INDIANB', 'MRF', 'MOTILALOFS', 'ASTRAL', 'NMDC', 'HEROMOTOCO', 'TATACOMM', 'BHEL', 'IRCTC', 'TATAINVEST', '360ONE', 'KEI', 'BANKINDIA', 'WAAREEENER', 'PHOENIXLTD', 'COROMANDEL', 'SBICARD', 'KPITTECH', 'NAUKRI', 'GMRAIRPORT', 'TATAELXSI', 'GROWW', 'MARICO', 'LICHSGFIN', 'BHARATFORG', 'GODREJPROP', 'MFSL', 'LUPIN', 'DABUR', 'COLPAL', 'POLICYBZR', 'PAGEIND', 'FORTIS', 'GLENMARK', 'SRF', 'SUPREMEIND', 'VMM', 'IDFCFIRSTB', 'ICICIGI', 'JSWENERGY', 'INDUSTOWER', 'OBEROIRLTY', 'MPHASIS', 'GVT&D', 'ATGL', 'ALKEM', 'CONCOR', 'SUZLON', 'MANKIND', 'EXIDEIND', 'TIINDIA', 'PIIND', 'PREMIERENE', 'VOLTAS', 'LAURUSLABS', 'RVNL'}
NIFTY_SMALLCAP_100_SYMBOLS: Set[str] = {'TATACHEM', 'DEVYANI', 'SAILIFE', 'AARTIIND', 'GESHIP', 'ASTERDM', 'BRIGADE', 'BANDHANBNK', 'SARDAEN', 'WHIRLPOOL', 'NAVINFLUOR', 'GMDCLTD', 'RBLBANK', 'APTUS', 'ITI', 'JBMA', 'BLS', 'AMBER', 'SWANCORP', 'CGCL', 'INOXWIND', 'TRITURBINE', 'TENNIND', 'JSWCEMENT', 'AFFLE', 'SONACOMS', 'PNBHOUSING', 'LALPATHLAB', 'DATAPATTNS', 'FSL', 'DEEPAKFERT', 'GPIL', 'WOCKPHARMA', 'CUB', 'NATCOPHARM', 'STARHEALTH', 'FORCEMOT', 'NEULANDLAB', 'TATATECH', 'URBANCO', 'PIRAMALFIN', 'GRSE', 'PPLPHARMA', 'HINDCOPPER', 'NETWEB', 'PWL', 'JYOTICNC', 'SIGNATURE', 'FIVESTAR', 'IGL', 'ANGELONE', 'MRPL', 'CHAMBLFERT', 'KAYNES', 'CDSL', 'RAMCOCEM', 'MEESHO', 'KEC', 'POONAWALLA', 'CAMS', 'COHANCE', 'CREDITACC', 'SYNGENE', 'NH', 'CESC', 'OLAELEC', 'HSCL', 'SAGILITY', 'IFCI', 'AEGISLOG', 'ABREL', 'IKS', 'ANANTRAJ', 'ANANDRATHI', 'KARURVYSYA', 'CASTROLIND', 'IDBI', 'NUVAMA', 'RPOWER', 'PGEL', 'FIRSTCRY', 'JMFINANCIL', 'CROMPTON', 'ARE&M', 'HBLENGINE', 'KFINTECH', 'WELCORP', 'DELHIVERY', 'REDINGTON', 'ZENSARTECH', 'NBCC', 'GLAND', 'IRCON', 'PINELABS', 'CHOLAHLDNG', 'BEML', 'MANAPPURAM', 'AFCONS', 'ATHERENERG', 'IIFL'}
NIFTY_TOTAL_MARKET_SYMBOLS: Set[str] = {'HAVELLS', 'SBIN', 'TATACHEM', 'AARTIIND', 'IOC', 'M&MFIN', 'SOBHA', 'HOMEFIRST', 'JSFB', 'BHARTIARTL', 'SOLARINDS', 'STYRENIX', 'WHIRLPOOL', 'JLHL', 'GMDCLTD', 'APTUS', 'SFL', 'ITI', 'DLF', 'IOB', 'NSLNISP', 'GALLANTT', 'UPL', 'HCG', 'AUBANK', 'AMBER', 'JUBLFOOD', 'SHAKTIPUMP', 'AARTIDRUGS', 'OLECTRA', 'MEDANTA', 'HGINFRA', 'OIL', 'TENNIND', 'OFSS', 'CEATLTD', 'LENSKART', 'SHILPAMED', 'SHRIRAMFIN', 'PNBHOUSING', 'ONGC', 'BBOX', 'ADANIGREEN', 'SKYGOLD', 'CANFINHOME', 'BLUEDART', 'ASHAPURMIN', 'ATLANTAELE', 'GHCL', 'ICIL', 'ATUL', 'CMSINFO', 'RITES', 'NEWGEN', 'DCBBANK', 'VIPIND', 'RAYMONDLSL', 'PTCIL', 'CUB', 'BECTORFOOD', 'BLUESTARCO', 'FINPIPE', 'HUDCO', 'PARKHOSPS', 'GNFC', 'AHLUCONT', 'LLOYDSENT', 'NATIONALUM', 'KITEX', 'AUROPHARMA', 'ACC', 'SAFARI', 'CEMPRO', 'CCL', 'NAM-INDIA', 'STYL', 'BSE', 'CUMMINSIND', 'URBANCO', 'TORNTPOWER', 'RECLTD', 'PPLPHARMA', 'INDIANB', 'ASHOKA', 'NIACL', 'GLAXO', 'SIGNATURE', 'FIVESTAR', 'GICRE', 'ITCHOTELS', 'IGL', 'MRF', 'CRAMC', 'FACT', '3MINDIA', 'MANORAMA', 'GODREJCP', 'SANDUMA', 'NMDC', 'GAEL', 'MEESHO', 'QPOWER', 'TARIL', 'HEROMOTOCO', 'QUESS', 'EMBDL', 'TECHNOE', 'KEI', 'USHAMART', 'STLTECH', 'MSUMI', 'CREDITACC', 'AVANTIFEED', 'ENGINERSIN', 'IXIGO', 'TRIVENI', 'CCAVENUE', 'SBICARD', 'VBL', 'BAYERCROP', 'DALBHARAT', 'GMRAIRPORT', 'NH', 'GROWW', 'VGUARD', 'SBILIFE', 'SPLPETRO', 'RCF', 'TTML', 'LICHSGFIN', 'UCOBANK', 'MFSL', 'ABSLAMC', 'NCC', 'LUPIN', 'RELIGARE', 'NTPC', 'LINDEINDIA', 'CHALET', 'MINDACORP', 'IFCI', 'ESCORTS', 'AEGISLOG', 'THELEELA', 'GSFC', 'SJVN', 'EMMVEE', 'TATASTEEL', 'DRREDDY', 'HAL', 'SRF', 'ABDL', 'BEL', 'VMM', 'HERITGFOOD', 'RPOWER', 'LATENTVIEW', 'HEXT', 'RUBICON', 'ACE', 'HYUNDAI', 'KSB', 'PTC', 'ARE&M', 'BORORENEW', 'GVT&D', 'WELCORP', 'PARAS', 'MASTEK', 'UNITDSPR', 'ZENSARTECH', 'ALKEM', 'CONCOR', 'J&KBANK', 'SUZLON', 'VTL', 'GLAND', 'KIMS', 'MANKIND', 'POWERGRID', 'ABB', 'IMFA', 'ALOKINDS', 'EXIDEIND', 'UTIAMC', 'CAMPUS', 'MANAPPURAM', 'AFCONS', 'SAMHI', 'CIPLA', 'MGL', 'BPCL', 'IIFL', 'CRIZAC', 'WAAREERTL', 'SHYAMMETL', 'RVNL', 'INDIACEM', 'BAJAJELEC', 'DEVYANI', 'GESHIP', 'MAXHEALTH', 'ANTHEM', 'GODFRYPHLP', 'SARDAEN', 'PAYTM', 'NAVINFLUOR', 'TIMETECHNO', 'JAMNAAUTO', 'HAPPSTMNDS', 'PERSISTENT', 'TATAPOWER', 'LLOYDSENGG', 'BALAMINES', 'MAHSEAMLES', 'ADANIENT', 'PRESTIGE', 'BLS', 'MIDHANI', 'WEBELSOLAR', 'IRB', 'BOSCHLTD', 'HDFCBANK', 'KSCL', 'HCLTECH', 'PIDILITIND', 'INOXWIND', 'CARBORUNIV', 'MSTCLTD', 'CAPILLARY', 'RALLIS', 'BAJAJ-AUTO', 'ABCAPITAL', 'ASAHIINDIA', 'RAIN', 'APLAPOLLO', 'ITC', 'POLYCAB', 'LALPATHLAB', 'JAIBALAJI', 'TIMKEN', 'SIEMENS', 'IREDA', 'FIEMIND', 'ALKYLAMINE', 'ZYDUSWELL', 'RENUKA', 'JYOTHYLAB', 'SWIGGY', 'DIXON', 'BALUFORGE', 'TRANSRAILL', 'CENTRALBK', 'AKUMS', 'SKFINDUS', 'LODHA', 'SCHAEFFLER', 'SCI', 'FEDERALBNK', 'SAPPHIRE', 'IFBIND', 'AVL', 'ONESOURCE', 'KIRLOSBROS', 'JWL', 'PRICOLLTD', 'BALRAMCHIN', 'ICICIBANK', 'SBFC', 'PRUDENT', 'JSL', 'AETHER', 'MMTC', 'INDIAMART', 'PWL', 'BALKRISIND', 'AVALON', 'NESCO', 'ARVIND', 'SUNDARMFIN', 'JINDALSAW', 'HDBFS', 'LOTUSDEV', 'SUNTV', 'SAATVIKGL', 'AGARWALEYE', 'MRPL', 'CHAMBLFERT', 'TATACONSUM', 'UJJIVANSFB', 'SUDEEPPHRM', 'DIACABS', 'RAMCOCEM', 'INTELLECT', 'DUMMYINGL1', 'TATACOMM', 'TATACAP', 'RELIANCE', 'GODREJIND', 'TCS', 'BHEL', 'IRCTC', '360ONE', 'INDIGOPNTS', 'WAAREEENER', 'PNB', 'TVSSCS', 'ZENTEC', 'WESTLIFE', 'HONASA', 'GRANULES', 'OPTIEMUS', 'APOLLOTYRE', 'KPITTECH', 'KRN', 'SMARTWORKS', 'TMCV', 'PCBL', 'PFIZER', 'VIKRAMSOLR', 'KPIGREEN', 'UTLSOLAR', 'AMBUJACEM', 'MARICO', 'SANSERA', 'DBL', 'BIRLACORPN', 'GODREJPROP', 'NTPCGREEN', 'DABUR', 'COLPAL', 'TMB', 'KPIL', 'GABRIEL', 'NAVA', 'RTNINDIA', 'PNCINFRA', 'GRINDWELL', 'HEGAM', 'PAGEIND', 'GOKEX', 'EMIL', 'IKS', 'DCMSHRIRAM', 'LTTS', 'TVSMOTOR', 'ALIVUS', 'HFCL', 'KAJARIACER', 'GLENMARK', 'KNRCON', 'ROUTE', 'CASTROLIND', 'IDBI', 'AAVAS', 'JKTYRE', 'IDFCFIRSTB', 'ICICIGI', 'OBEROIRLTY', 'FIRSTCRY', 'BANCOINDIA', 'CROMPTON', 'AIIL', 'ATGL', 'HBLENGINE', 'RATNAMANI', 'DELHIVERY', 'LTFOODS', 'EDELWEISS', 'ORIENTCEM', 'ECLERX', 'REDINGTON', 'GOKULAGRO', 'RKFORGE', 'REFEX', 'IRCON', 'TBOTEK', 'ANUP', 'AIAENG', 'BANKBARODA', 'JINDALSTEL', 'CLEAN', 'CELLO', 'SUMICHEM', 'CHOLAFIN', 'PREMIERENE', 'PICCADIL', 'DUMMYINGL2', 'DEEPAKNTR', 'ADANIENSOL', 'INDIGO', 'TECHM', 'BIOCON', 'SAILIFE', 'HINDPETRO', 'FEDFINA', 'HDFCAMC', 'ICICIAMC', 'POLYMED', 'TMPV', 'TEJASNET', 'CSBBANK', 'DIVISLAB', 'TDPOWERSYS', 'EMCURE', 'IPCALAB', 'RBLBANK', 'FLUOROCHEM', 'MAHSCOOTER', 'JBMA', 'SOUTHBANK', 'SAIL', 'ZYDUSLIFE', 'APOLLOHOSP', 'ENDURANCE', 'VARROC', 'SWANCORP', 'KALYANKJIL', 'SCHNEIDER', 'MCX', 'HINDUNILVR', 'TRITURBINE', 'GODREJAGRO', 'YESBANK', 'AFFLE', 'GRASIM', 'BLUEJET', 'ETERNAL', 'SONACOMS', 'JKPAPER', 'TRENT', 'ULTRACEMCO', 'SUBROS', 'BERGEPAINT', 'FSL', 'REDTAPE', 'BHARTIHEXA', 'EICHERMOT', 'JUSTDIAL', 'BDL', 'GPIL', 'JKLAKSHMI', 'ENRIN', 'PATANJALI', 'COCHINSHIP', 'SURYAROSNI', 'STARHEALTH', 'ELGIEQUIP', 'FORCEMOT', 'INDUSINDBK', 'M&M', 'HDFCLIFE', 'IGIL', 'STAR', 'LGEINDIA', 'NLCINDIA', 'GRSE', 'KANSAINER', 'INOXINDIA', 'HINDCOPPER', 'NETWEB', 'THANGAMAYL', 'JYOTICNC', 'DATAMATICS', 'EIDPARRY', 'DYNAMATECH', 'MTARTECH', 'RBA', 'AEQUS', 'CHENNPETRO', 'GRAVITA', 'CRAFTSMAN', 'ASTRAL', 'SHREECEM', 'BRITANNIA', 'KAYNES', 'NEOGEN', 'CDSL', 'THOMASCOOK', 'CIEINDIA', 'MARUTI', 'INDIASHLTR', 'DOMS', 'MANYAVAR', 'HCC', 'OSWALPUMPS', 'JPPOWER', 'EPL', 'COHANCE', 'ACMESOLAR', 'NETWORK18', 'STARCEMENT', 'PFOCUS', 'COROMANDEL', 'HINDZINC', 'SYNGENE', 'SYRMA', 'NAUKRI', 'VIJAYA', 'SPARC', 'IONEXCHANG', 'YATHARTH', 'CESC', 'EMAMILTD', 'ENTERO', 'INDGN', 'THYROCARE', 'KIRLPNU', 'LXCHEM', 'CORONA', 'SANOFICONR', 'PURVA', 'AXISBANK', 'AXISCADES', 'LEMONTREE', 'TITAGARH', 'EIEL', 'PNGJL', 'TRIDENT', 'GMRP&UI', 'PFC', 'EQUITASBNK', 'VOLTAMP', 'SAGILITY', 'JKCEMENT', 'BLUESTONE', 'POLICYBZR', 'BSOFT', 'ADANIPOWER', 'ARVINDFASN', 'ADVENZYMES', 'BBTC', 'TEGA', 'ANANTRAJ', 'POWERMECH', 'ANANDRATHI', 'RRKABEL', 'SUPREMEIND', 'SHAILY', 'JIOFIN', 'JSWENERGY', 'PGEL', 'ASKAUTOLTD', 'UBL', 'THERMAX', 'WABAG', 'CRISIL', 'WAKEFIT', 'CERA', 'MPHASIS', 'GPPL', 'VEDL', 'MEDPLUS', 'RAILTEL', 'LLOYDSME', 'LTM', 'BAJAJFINSV', 'APARINDS', 'HONAUT', 'ZEEL', 'GRAPHITE', 'KPRMILL', 'CANHLIFE', 'MARKSANS', 'PCJEWELLER', 'ACI', 'WEWORK', 'PIIND', 'VOLTAS', 'ANURAS', 'NIVABUPA', 'ASHOKLEY', 'ELECON', 'LICI', 'ASTERDM', 'BRIGADE', 'APOLLO', 'BANDHANBNK', 'TANLA', 'MAZDOCK', 'ELECTCAST', 'ETHOSLTD', 'NHPC', 'LTF', 'ASIANPAINT', 'IRFC', 'ZFCVINDIA', 'FINCABLES', 'ICICIPRULI', 'LUMAXTECH', 'TARC', 'BIKAJI', 'RELAXO', 'SAMMAANCAP', 'GREAVESCOT', 'ABLBL', 'CGCL', 'SMLMAH', 'JSLL', 'SONATSOFTW', 'JSWCEMENT', 'AURIONPRO', 'BAJFINANCE', 'UNOMINDA', 'INOXGREEN', 'ORKLAINDIA', 'POWERINDIA', 'TIPSMUSIC', 'UNIONBANK', 'DATAPATTNS', 'GODIGIT', 'ABBOTINDIA', 'SUPRIYA', 'BAJAJHFL', 'DEEPAKFERT', 'JAINREC', 'PARADEEP', 'MOIL', 'KOTAKBANK', 'NAZARA', 'RATEGAIN', 'WOCKPHARMA', 'NATCOPHARM', 'CPPLUS', 'MOTHERSON', 'BAJAJHLDNG', 'PVRINOX', 'NEULANDLAB', 'NYKAA', 'RADICO', 'ASTRAMICRO', 'TATATECH', 'CUPID', 'PIRAMALFIN', 'IDEA', 'METROPOLIS', 'RHIM', 'TEXRAIL', 'COFORGE', 'SHRIPISTON', 'DUMMYHEG', 'TRAVELFOOD', 'WIPRO', 'MAPMYINDIA', 'ANGELONE', 'RAINBOW', 'CONCORDBIO', 'HEMIPROP', 'MOTILALOFS', 'SUDARSCHEM', 'CARTRADE', 'CENTURYPLY', 'NUVOCO', 'ELLEN', 'DBREALTY', 'SKFINDIA', 'INDIAGLYCO', 'KEC', 'TATAINVEST', 'DMART', 'POONAWALLA', 'CAMS', 'AZAD', 'BANKINDIA', 'JSWINFRA', 'COALINDIA', 'SUNTECK', 'ABFRL', 'TI', 'MAHABANK', 'PHOENIXLTD', 'SKIPPER', 'AWFIS', 'GMMPFAUDLR', 'WELENT', 'ACUTAAS', 'TATAELXSI', 'INFY', 'TSFINV', 'V2RETAIL', 'CAPLIPOINT', 'JUBLINGREA', 'AARTIPHARM', 'ADANIPORTS', 'OLAELEC', 'PRAJIND', 'KTKBANK', 'BHARATFORG', 'NFL', 'BATAINDIA', 'DUMMYTRVN', 'EIHOTEL', 'SWSOLAR', 'HSCL', 'PRSMJOHNSN', 'AJANTPHARM', 'SHAREINDIA', 'AWL', 'CGPOWER', 'TITAN', 'BLACKBUCK', 'ERIS', 'INDHOTEL', 'JSWSTEEL', 'SAREGAMA', 'GAIL', 'LT', 'ABREL', 'FORTIS', 'PGIL', 'KARURVYSYA', 'DUMMYINXGN', 'VIYASH', 'GRWRHITECH', 'SHARDACROP', 'NUVAMA', 'IEX', 'INDUSTOWER', 'SENCO', 'VMART', 'TORNTPHARM', 'VAIBHAVGBL', 'KIRLOSENG', 'EUREKAFORB', 'JMFINANCIL', 'JUBLPHARMA', 'SUNPHARMA', 'JSWDULUX', 'KFINTECH', 'CANBK', 'JAYNECOIND', 'CHOICEIN', 'WELSPUNLIV', 'AADHARHFC', 'BELRISE', 'AEGISVOPAK', 'NBCC', 'GILLETTE', 'KRBL', 'PETRONET', 'PINELABS', 'CHOLAHLDNG', 'BEML', 'IIFLCAPS', 'TIINDIA', 'APLLTD', 'ZAGGLE', 'MUTHOOTFIN', 'PRIVISCL', 'RTNPOWER', 'ATHERENERG', 'CYIENT', 'NESTLEIND', 'HINDALCO', 'LAURUSLABS'}

COMPANY_NAMES_MAP: Dict[str, str] = {
    "ADANIENT": "Adani Enterprises Ltd.",
    "ADANIPORTS": "Adani Ports and Special Economic Zone Ltd.",
    "APOLLOHOSP": "Apollo Hospitals Enterprise Ltd.",
    "ASIANPAINT": "Asian Paints Ltd.",
    "AXISBANK": "Axis Bank Ltd.",
    "BAJAJ-AUTO": "Bajaj Auto Ltd.",
    "BAJFINANCE": "Bajaj Finance Ltd.",
    "BAJAJFINSV": "Bajaj Finserv Ltd.",
    "BEL": "Bharat Electronics Ltd.",
    "BHARTIARTL": "Bharti Airtel Ltd.",
    "CIPLA": "Cipla Ltd.",
    "COALINDIA": "Coal India Ltd.",
    "DRREDDY": "Dr. Reddy's Laboratories Ltd.",
    "EICHERMOT": "Eicher Motors Ltd.",
    "ETERNAL": "Eternal Ltd.",
    "GRASIM": "Grasim Industries Ltd.",
    "HCLTECH": "HCL Technologies Ltd.",
    "HDFCBANK": "HDFC Bank Ltd.",
    "HDFCLIFE": "HDFC Life Insurance Company Ltd.",
    "HINDALCO": "Hindalco Industries Ltd.",
    "HINDUNILVR": "Hindustan Unilever Ltd.",
    "ICICIBANK": "ICICI Bank Ltd.",
    "ITC": "ITC Ltd.",
    "INFY": "Infosys Ltd.",
    "INDIGO": "InterGlobe Aviation Ltd.",
    "JSWSTEEL": "JSW Steel Ltd.",
    "JIOFIN": "Jio Financial Services Ltd.",
    "KOTAKBANK": "Kotak Mahindra Bank Ltd.",
    "LT": "Larsen & Toubro Ltd.",
    "M&M": "Mahindra & Mahindra Ltd.",
    "MARUTI": "Maruti Suzuki India Ltd.",
    "MAXHEALTH": "Max Healthcare Institute Ltd.",
    "NTPC": "NTPC Ltd.",
    "NESTLEIND": "Nestle India Ltd.",
    "ONGC": "Oil & Natural Gas Corporation Ltd.",
    "POWERGRID": "Power Grid Corporation of India Ltd.",
    "RELIANCE": "Reliance Industries Ltd.",
    "SBILIFE": "SBI Life Insurance Company Ltd.",
    "SHRIRAMFIN": "Shriram Finance Ltd.",
    "SBIN": "State Bank of India",
    "SUNPHARMA": "Sun Pharmaceutical Industries Ltd.",
    "TCS": "Tata Consultancy Services Ltd.",
    "TATACONSUM": "Tata Consumer Products Ltd.",
    "TMPV": "Tata Motors Passenger Vehicles Ltd.",
    "TATASTEEL": "Tata Steel Ltd.",
    "TECHM": "Tech Mahindra Ltd.",
    "TITAN": "Titan Company Ltd.",
    "TRENT": "Trent Ltd.",
    "ULTRACEMCO": "UltraTech Cement Ltd.",
    "WIPRO": "Wipro Ltd.",
    "ABB": "ABB India Ltd.",
    "ADANIENSOL": "Adani Energy Solutions Ltd.",
    "ADANIGREEN": "Adani Green Energy Ltd.",
    "ADANIPOWER": "Adani Power Ltd.",
    "AMBUJACEM": "Ambuja Cements Ltd.",
    "DMART": "Avenue Supermarts Ltd.",
    "BAJAJHLDNG": "Bajaj Holdings & Investment Ltd.",
    "BANKBARODA": "Bank of Baroda",
    "BPCL": "Bharat Petroleum Corporation Ltd.",
    "BOSCHLTD": "Bosch Ltd.",
    "BRITANNIA": "Britannia Industries Ltd.",
    "CGPOWER": "CG Power and Industrial Solutions Ltd.",
    "CANBK": "Canara Bank",
    "CHOLAFIN": "Cholamandalam Investment and Finance Company Ltd.",
    "CUMMINSIND": "Cummins India Ltd.",
    "DLF": "DLF Ltd.",
    "DIVISLAB": "Divi's Laboratories Ltd.",
    "GAIL": "GAIL (India) Ltd.",
    "GODREJCP": "Godrej Consumer Products Ltd.",
    "HDFCAMC": "HDFC Asset Management Company Ltd.",
    "HAL": "Hindustan Aeronautics Ltd.",
    "HINDZINC": "Hindustan Zinc Ltd.",
    "HYUNDAI": "Hyundai Motor India Ltd.",
    "INDHOTEL": "Indian Hotels Co. Ltd.",
    "IOC": "Indian Oil Corporation Ltd.",
    "IRFC": "Indian Railway Finance Corporation Ltd.",
    "JINDALSTEL": "Jindal Steel Ltd.",
    "LTM": "LTM Ltd.",
    "LODHA": "Lodha Developers Ltd.",
    "MAZDOCK": "Mazagoan Dock Shipbuilders Ltd.",
    "MUTHOOTFIN": "Muthoot Finance Ltd.",
    "PIDILITIND": "Pidilite Industries Ltd.",
    "PFC": "Power Finance Corporation Ltd.",
    "PNB": "Punjab National Bank",
    "RECLTD": "REC Ltd.",
    "MOTHERSON": "Samvardhana Motherson International Ltd.",
    "SHREECEM": "Shree Cement Ltd.",
    "ENRIN": "Siemens Energy India Ltd.",
    "SIEMENS": "Siemens Ltd.",
    "SOLARINDS": "Solar Industries India Ltd.",
    "TVSMOTOR": "TVS Motor Company Ltd.",
    "TATACAP": "Tata Capital Ltd.",
    "TMCV": "Tata Motors Ltd.",
    "TATAPOWER": "Tata Power Co. Ltd.",
    "TORNTPHARM": "Torrent Pharmaceuticals Ltd.",
    "UNIONBANK": "Union Bank of India",
    "UNITDSPR": "United Spirits Ltd.",
    "VBL": "Varun Beverages Ltd.",
    "VEDL": "Vedanta Ltd.",
    "ZYDUSLIFE": "Zydus Lifesciences Ltd.",
    "360ONE": "360 ONE WAM Ltd.",
    "3MINDIA": "3M India Ltd.",
    "ACC": "ACC Ltd.",
    "ACMESOLAR": "ACME Solar Holdings Ltd.",
    "AIAENG": "AIA Engineering Ltd.",
    "APLAPOLLO": "APL Apollo Tubes Ltd.",
    "AUBANK": "AU Small Finance Bank Ltd.",
    "AWL": "AWL Agri Business Ltd.",
    "AADHARHFC": "Aadhar Housing Finance Ltd.",
    "AARTIIND": "Aarti Industries Ltd.",
    "AAVAS": "Aavas Financiers Ltd.",
    "ABBOTINDIA": "Abbott India Ltd.",
    "ACE": "Action Construction Equipment Ltd.",
    "ACUTAAS": "Acutaas Chemicals Ltd.",
    "ATGL": "Adani Total Gas Ltd.",
    "ABCAPITAL": "Aditya Birla Capital Ltd.",
    "ABFRL": "Aditya Birla Fashion and Retail Ltd.",
    "ABLBL": "Aditya Birla Lifestyle Brands Ltd.",
    "ABREL": "Aditya Birla Real Estate Ltd.",
    "ABSLAMC": "Aditya Birla Sun Life AMC Ltd.",
    "CPPLUS": "Aditya Infotech Ltd.",
    "AEGISLOG": "Aegis Logistics Ltd.",
    "AEGISVOPAK": "Aegis Vopak Terminals Ltd.",
    "AFCONS": "Afcons Infrastructure Ltd.",
    "AFFLE": "Affle 3i Ltd.",
    "AJANTPHARM": "Ajanta Pharmaceuticals Ltd.",
    "ALKEM": "Alkem Laboratories Ltd.",
    "ABDL": "Allied Blenders and Distillers Ltd.",
    "ARE&M": "Amara Raja Energy & Mobility Ltd.",
    "AMBER": "Amber Enterprises India Ltd.",
    "ANANDRATHI": "Anand Rathi Wealth Ltd.",
    "ANANTRAJ": "Anant Raj Ltd.",
    "ANGELONE": "Angel One Ltd.",
    "ANTHEM": "Anthem Biosciences Ltd.",
    "ANURAS": "Anupam Rasayan India Ltd.",
    "APARINDS": "Apar Industries Ltd.",
    "APOLLOTYRE": "Apollo Tyres Ltd.",
    "APTUS": "Aptus Value Housing Finance India Ltd.",
    "ASAHIINDIA": "Asahi India Glass Ltd.",
    "ASHOKLEY": "Ashok Leyland Ltd.",
    "ASTERDM": "Aster DM Quality Care Ltd.",
    "ASTRAL": "Astral Ltd.",
    "ATHERENERG": "Ather Energy Ltd.",
    "ATUL": "Atul Ltd.",
    "AUROPHARMA": "Aurobindo Pharma Ltd.",
    "AIIL": "Authum Investment & Infrastructure Ltd.",
    "BEML": "BEML Ltd.",
    "BLS": "BLS International Services Ltd.",
    "BSE": "BSE Ltd.",
    "BAJAJHFL": "Bajaj Housing Finance Ltd.",
    "BALKRISIND": "Balkrishna Industries Ltd.",
    "BALRAMCHIN": "Balrampur Chini Mills Ltd.",
    "BANDHANBNK": "Bandhan Bank Ltd.",
    "BANKINDIA": "Bank of India",
    "MAHABANK": "Bank of Maharashtra",
    "BATAINDIA": "Bata India Ltd.",
    "BAYERCROP": "Bayer Cropscience Ltd.",
    "BELRISE": "Belrise Industries Ltd.",
    "BERGEPAINT": "Berger Paints India Ltd.",
    "BDL": "Bharat Dynamics Ltd.",
    "BHARATFORG": "Bharat Forge Ltd.",
    "BHEL": "Bharat Heavy Electricals Ltd.",
    "BHARTIHEXA": "Bharti Hexacom Ltd.",
    "BIKAJI": "Bikaji Foods International Ltd.",
    "GROWW": "Billionbrains Garage Ventures Ltd.",
    "BIOCON": "Biocon Ltd.",
    "BSOFT": "Birlasoft Ltd.",
    "BLUEDART": "Blue Dart Express Ltd.",
    "BLUEJET": "Blue Jet Healthcare Ltd.",
    "BLUESTARCO": "Blue Star Ltd.",
    "BBTC": "Bombay Burmah Trading Corporation Ltd.",
    "FIRSTCRY": "Brainbees Solutions Ltd.",
    "BRIGADE": "Brigade Enterprises Ltd.",
    "MAPMYINDIA": "C.E. Info Systems Ltd.",
    "CCL": "CCL Products (I) Ltd.",
    "CESC": "CESC Ltd.",
    "CIEINDIA": "CIE Automotive India Ltd.",
    "CRISIL": "CRISIL Ltd.",
    "CANFINHOME": "Can Fin Homes Ltd.",
    "CANHLIFE": "Canara HSBC Life Insurance Company Ltd.",
    "CAPLIPOINT": "Caplin Point Laboratories Ltd.",
    "CGCL": "Capri Global Capital Ltd.",
    "CARBORUNIV": "Carborundum Universal Ltd.",
    "CARTRADE": "Cartrade Tech Ltd.",
    "CASTROLIND": "Castrol India Ltd.",
    "CEATLTD": "Ceat Ltd.",
    "CEMPRO": "Cemindia Projects Ltd.",
    "CENTRALBK": "Central Bank of India",
    "CDSL": "Central Depository Services (India) Ltd.",
    "CHALET": "Chalet Hotels Ltd.",
    "CHAMBLFERT": "Chambal Fertilizers & Chemicals Ltd.",
    "CHENNPETRO": "Chennai Petroleum Corporation Ltd.",
    "CHOICEIN": "Choice International Ltd.",
    "CHOLAHLDNG": "Cholamandalam Financial Holdings Ltd.",
    "CUB": "City Union Bank Ltd.",
    "CLEAN": "Clean Science and Technology Ltd.",
    "COCHINSHIP": "Cochin Shipyard Ltd.",
    "COFORGE": "Coforge Ltd.",
    "COHANCE": "Cohance Lifesciences Ltd.",
    "COLPAL": "Colgate Palmolive (India) Ltd.",
    "CAMS": "Computer Age Management Services Ltd.",
    "CONCORDBIO": "Concord Biotech Ltd.",
    "CONCOR": "Container Corporation of India Ltd.",
    "COROMANDEL": "Coromandel International Ltd.",
    "CRAFTSMAN": "Craftsman Automation Ltd.",
    "CREDITACC": "CreditAccess Grameen Ltd.",
    "CROMPTON": "Crompton Greaves Consumer Electricals Ltd.",
    "CYIENT": "Cyient Ltd.",
    "DCMSHRIRAM": "DCM Shriram Ltd.",
    "DOMS": "DOMS Industries Ltd.",
    "DABUR": "Dabur India Ltd.",
    "DALBHARAT": "Dalmia Bharat Ltd.",
    "DATAPATTNS": "Data Patterns (India) Ltd.",
    "DEEPAKFERT": "Deepak Fertilisers & Petrochemicals Corp. Ltd.",
    "DEEPAKNTR": "Deepak Nitrite Ltd.",
    "DELHIVERY": "Delhivery Ltd.",
    "DEVYANI": "Devyani International Ltd.",
    "DIXON": "Dixon Technologies (India) Ltd.",
    "LALPATHLAB": "Dr. Lal Path Labs Ltd.",
    "DUMMYHEG": "Dummy HEG Ltd.",
    "EIDPARRY": "E.I.D. Parry (India) Ltd.",
    "EIHOTEL": "EIH Ltd.",
    "ELECON": "Elecon Engineering Co. Ltd.",
    "ELGIEQUIP": "Elgi Equipments Ltd.",
    "EMAMILTD": "Emami Ltd.",
    "EMCURE": "Emcure Pharmaceuticals Ltd.",
    "EMMVEE": "Emmvee Photovoltaic Power Ltd.",
    "ENDURANCE": "Endurance Technologies Ltd.",
    "ENGINERSIN": "Engineers India Ltd.",
    "ERIS": "Eris Lifesciences Ltd.",
    "ESCORTS": "Escorts Kubota Ltd.",
    "EXIDEIND": "Exide Industries Ltd.",
    "NYKAA": "FSN E-Commerce Ventures Ltd.",
    "FEDERALBNK": "Federal Bank Ltd.",
    "FACT": "Fertilisers and Chemicals Travancore Ltd.",
    "FINCABLES": "Finolex Cables Ltd.",
    "FSL": "Firstsource Solutions Ltd.",
    "FIVESTAR": "Five-Star Business Finance Ltd.",
    "FORCEMOT": "Force Motors Ltd.",
    "FORTIS": "Fortis Healthcare Ltd.",
    "GVT&D": "GE Vernova T&D India Ltd.",
    "GMRAIRPORT": "GMR Airports Ltd.",
    "GABRIEL": "Gabriel India Ltd.",
    "GALLANTT": "Gallantt Ispat Ltd.",
    "GRSE": "Garden Reach Shipbuilders & Engineers Ltd.",
    "GICRE": "General Insurance Corporation of India",
    "GILLETTE": "Gillette India Ltd.",
    "GLAND": "Gland Pharma Ltd.",
    "GLAXO": "Glaxosmithkline Pharmaceuticals Ltd.",
    "GLENMARK": "Glenmark Pharmaceuticals Ltd.",
    "MEDANTA": "Global Health Ltd.",
    "GODIGIT": "Go Digit General Insurance Ltd.",
    "GPIL": "Godawari Power & Ispat Ltd.",
    "GODFRYPHLP": "Godfrey Phillips India Ltd.",
    "GODREJIND": "Godrej Industries Ltd.",
    "GODREJPROP": "Godrej Properties Ltd.",
    "GRANULES": "Granules India Ltd.",
    "GRAPHITE": "Graphite India Ltd.",
    "GRAVITA": "Gravita India Ltd.",
    "GESHIP": "Great Eastern Shipping Co. Ltd.",
    "FLUOROCHEM": "Gujarat Fluorochemicals Ltd.",
    "GMDCLTD": "Gujarat Mineral Development Corporation Ltd.",
    "HBLENGINE": "HBL Engineering Ltd.",
    "HDBFS": "HDB Financial Services Ltd.",
    "HEGAM": "HEG Advanced Materials Ltd.",
    "HFCL": "HFCL Ltd.",
    "HAVELLS": "Havells India Ltd.",
    "HEROMOTOCO": "Hero MotoCorp Ltd.",
    "HEXT": "Hexaware Technologies Ltd.",
    "HSCL": "Himadri Speciality Chemical Ltd.",
    "HINDCOPPER": "Hindustan Copper Ltd.",
    "HINDPETRO": "Hindustan Petroleum Corporation Ltd.",
    "POWERINDIA": "Hitachi Energy India Ltd.",
    "HOMEFIRST": "Home First Finance Company India Ltd.",
    "HONASA": "Honasa Consumer Ltd.",
    "HONAUT": "Honeywell Automation India Ltd.",
    "HUDCO": "Housing & Urban Development Corporation Ltd.",
    "ICICIGI": "ICICI Lombard General Insurance Company Ltd.",
    "ICICIAMC": "ICICI Prudential Asset Management Company Ltd.",
    "ICICIPRULI": "ICICI Prudential Life Insurance Company Ltd.",
    "IDBI": "IDBI Bank Ltd.",
    "IDFCFIRSTB": "IDFC First Bank Ltd.",
    "IFCI": "IFCI Ltd.",
    "IIFL": "IIFL Finance Ltd.",
    "IRB": "IRB Infrastructure Developers Ltd.",
    "IRCON": "IRCON International Ltd.",
    "ITCHOTELS": "ITC Hotels Ltd.",
    "ITI": "ITI Ltd.",
    "INDGN": "Indegene Ltd.",
    "INDIACEM": "India Cements Ltd.",
    "INDIAMART": "Indiamart Intermesh Ltd.",
    "INDIANB": "Indian Bank",
    "IEX": "Indian Energy Exchange Ltd.",
    "IOB": "Indian Overseas Bank",
    "IRCTC": "Indian Railway Catering And Tourism Corporation Ltd.",
    "IREDA": "Indian Renewable Energy Development Agency Ltd.",
    "IGL": "Indraprastha Gas Ltd.",
    "INDUSTOWER": "Indus Towers Ltd.",
    "INDUSINDBK": "IndusInd Bank Ltd.",
    "NAUKRI": "Info Edge (India) Ltd.",
    "INOXWIND": "Inox Wind Ltd.",
    "INTELLECT": "Intellect Design Arena Ltd.",
    "IGIL": "International Gemological Institute Ltd.",
    "IKS": "Inventurus Knowledge Solutions Ltd.",
    "IPCALAB": "Ipca Laboratories Ltd.",
    "JKCEMENT": "J.K. Cement Ltd.",
    "JBMA": "JBM Auto Ltd.",
    "JKTYRE": "JK Tyre & Industries Ltd.",
    "JMFINANCIL": "JM Financial Ltd.",
    "JSWCEMENT": "JSW Cement Ltd.",
    "JSWDULUX": "JSW Dulux Ltd.",
    "JSWENERGY": "JSW Energy Ltd.",
    "JSWINFRA": "JSW Infrastructure Ltd.",
    "JAINREC": "Jain Resource Recycling Ltd.",
    "JPPOWER": "Jaiprakash Power Ventures Ltd.",
    "J&KBANK": "Jammu & Kashmir Bank Ltd.",
    "JINDALSAW": "Jindal Saw Ltd.",
    "JSL": "Jindal Stainless Ltd.",
    "JUBLFOOD": "Jubilant Foodworks Ltd.",
    "JUBLINGREA": "Jubilant Ingrevia Ltd.",
    "JUBLPHARMA": "Jubilant Pharmova Ltd.",
    "JWL": "Jupiter Wagons Ltd.",
    "JYOTICNC": "Jyoti CNC Automation Ltd.",
    "KPRMILL": "K.P.R. Mill Ltd.",
    "KEI": "KEI Industries Ltd.",
    "KPITTECH": "KPIT Technologies Ltd.",
    "KAJARIACER": "Kajaria Ceramics Ltd.",
    "KPIL": "Kalpataru Projects International Ltd.",
    "KALYANKJIL": "Kalyan Jewellers India Ltd.",
    "KARURVYSYA": "Karur Vysya Bank Ltd.",
    "KAYNES": "Kaynes Technology India Ltd.",
    "KEC": "Kec International Ltd.",
    "KFINTECH": "Kfin Technologies Ltd.",
    "KIRLOSENG": "Kirloskar Oil Eng Ltd.",
    "KIMS": "Krishna Institute of Medical Sciences Ltd.",
    "LTF": "L&T Finance Ltd.",
    "LTTS": "L&T Technology Services Ltd.",
    "LGEINDIA": "LG Electronics India Ltd.",
    "LICHSGFIN": "LIC Housing Finance Ltd.",
    "LTFOODS": "LT Foods Ltd.",
    "LATENTVIEW": "Latent View Analytics Ltd.",
    "LAURUSLABS": "Laurus Labs Ltd.",
    "THELEELA": "Leela Palaces Hotels & Resorts Ltd.",
    "LEMONTREE": "Lemon Tree Hotels Ltd.",
    "LENSKART": "Lenskart Solutions Ltd.",
    "LICI": "Life Insurance Corporation of India",
    "LINDEINDIA": "Linde India Ltd.",
    "LLOYDSME": "Lloyds Metals And Energy Ltd.",
    "LUPIN": "Lupin Ltd.",
    "MMTC": "MMTC Ltd.",
    "MRF": "MRF Ltd.",
    "MGL": "Mahanagar Gas Ltd.",
    "M&MFIN": "Mahindra & Mahindra Financial Services Ltd.",
    "MANAPPURAM": "Manappuram Finance Ltd.",
    "MRPL": "Mangalore Refinery & Petrochemicals Ltd.",
    "MANKIND": "Mankind Pharma Ltd.",
    "MARICO": "Marico Ltd.",
    "MFSL": "Max Financial Services Ltd.",
    "MEESHO": "Meesho Ltd.",
    "MINDACORP": "Minda Corporation Ltd.",
    "MSUMI": "Motherson Sumi Wiring India Ltd.",
    "MOTILALOFS": "Motilal Oswal Financial Services Ltd.",
    "MPHASIS": "MphasiS Ltd.",
    "MCX": "Multi Commodity Exchange of India Ltd.",
    "NATCOPHARM": "NATCO Pharma Ltd.",
    "NBCC": "NBCC (India) Ltd.",
    "NCC": "NCC Ltd.",
    "NHPC": "NHPC Ltd.",
    "NLCINDIA": "NLC India Ltd.",
    "NMDC": "NMDC Ltd.",
    "NSLNISP": "NMDC Steel Ltd.",
    "NTPCGREEN": "NTPC Green Energy Ltd.",
    "NH": "Narayana Hrudayalaya Ltd.",
    "NATIONALUM": "National Aluminium Co. Ltd.",
    "NAVA": "Nava Ltd.",
    "NAVINFLUOR": "Navin Fluorine International Ltd.",
    "NETWEB": "Netweb Technologies India Ltd.",
    "NEULANDLAB": "Neuland Laboratories Ltd.",
    "NEWGEN": "Newgen Software Technologies Ltd.",
    "NAM-INDIA": "Nippon Life India Asset Management Ltd.",
    "NIVABUPA": "Niva Bupa Health Insurance Company Ltd.",
    "NUVAMA": "Nuvama Wealth Management Ltd.",
    "NUVOCO": "Nuvoco Vistas Corporation Ltd.",
    "OBEROIRLTY": "Oberoi Realty Ltd.",
    "OIL": "Oil India Ltd.",
    "OLAELEC": "Ola Electric Mobility Ltd.",
    "OLECTRA": "Olectra Greentech Ltd.",
    "PAYTM": "One 97 Communications Ltd.",
    "ONESOURCE": "Onesource Specialty Pharma Ltd.",
    "OFSS": "Oracle Financial Services Software Ltd.",
    "POLICYBZR": "PB Fintech Ltd.",
    "PCBL": "PCBL Chemical Ltd.",
    "PGEL": "PG Electroplast Ltd.",
    "PIIND": "PI Industries Ltd.",
    "PNBHOUSING": "PNB Housing Finance Ltd.",
    "PTCIL": "PTC Industries Ltd.",
    "PVRINOX": "PVR INOX Ltd.",
    "PAGEIND": "Page Industries Ltd.",
    "PARADEEP": "Paradeep Phosphates Ltd.",
    "PATANJALI": "Patanjali Foods Ltd.",
    "PERSISTENT": "Persistent Systems Ltd.",
    "PETRONET": "Petronet LNG Ltd.",
    "PFIZER": "Pfizer Ltd.",
    "PHOENIXLTD": "Phoenix Mills Ltd.",
    "PWL": "Physicswallah Ltd.",
    "PINELABS": "Pine Labs Ltd.",
    "PIRAMALFIN": "Piramal Finance Ltd.",
    "PPLPHARMA": "Piramal Pharma Ltd.",
    "POLYMED": "Poly Medicure Ltd.",
    "POLYCAB": "Polycab India Ltd.",
    "POONAWALLA": "Poonawalla Fincorp Ltd.",
    "PREMIERENE": "Premier Energies Ltd.",
    "PRESTIGE": "Prestige Estates Projects Ltd.",
    "PFOCUS": "Prime Focus Ltd.",
    "RRKABEL": "R R Kabel Ltd.",
    "RBLBANK": "RBL Bank Ltd.",
    "RHIM": "RHI MAGNESITA INDIA LTD.",
    "RITES": "RITES Ltd.",
    "RADICO": "Radico Khaitan Ltd",
    "RVNL": "Rail Vikas Nigam Ltd.",
    "RAILTEL": "Railtel Corporation Of India Ltd.",
    "RAINBOW": "Rainbow Childrens Medicare Ltd.",
    "RKFORGE": "Ramkrishna Forgings Ltd.",
    "REDINGTON": "Redington Ltd.",
    "RPOWER": "Reliance Power Ltd.",
    "SBFC": "SBFC Finance Ltd.",
    "SBICARD": "SBI Cards and Payment Services Ltd.",
    "SJVN": "SJVN Ltd.",
    "SRF": "SRF Ltd.",
    "SAGILITY": "Sagility Ltd.",
    "SAILIFE": "Sai Life Sciences Ltd.",
    "SAMMAANCAP": "Sammaan Capital Ltd.",
    "SAPPHIRE": "Sapphire Foods India Ltd.",
    "SARDAEN": "Sarda Energy and Minerals Ltd.",
    "SAREGAMA": "Saregama India Ltd",
    "SCHAEFFLER": "Schaeffler India Ltd.",
    "SCHNEIDER": "Schneider Electric Infrastructure Ltd.",
    "SCI": "Shipping Corporation of India Ltd.",
    "SHYAMMETL": "Shyam Metalics and Energy Ltd.",
    "SIGNATURE": "Signatureglobal (India) Ltd.",
    "SOBHA": "Sobha Ltd.",
    "SONACOMS": "Sona BLW Precision Forgings Ltd.",
    "SONATSOFTW": "Sonata Software Ltd.",
    "STARHEALTH": "Star Health and Allied Insurance Company Ltd.",
    "SAIL": "Steel Authority of India Ltd.",
    "SUMICHEM": "Sumitomo Chemical India Ltd.",
    "SUNTV": "Sun TV Network Ltd.",
    "SUNDARMFIN": "Sundaram Finance Ltd.",
    "SUPREMEIND": "Supreme Industries Ltd.",
    "SPLPETRO": "Supreme Petrochem Ltd.",
    "SUZLON": "Suzlon Energy Ltd.",
    "SWANCORP": "Swan Corp Ltd.",
    "SWIGGY": "Swiggy Ltd.",
    "SYNGENE": "Syngene International Ltd.",
    "SYRMA": "Syrma SGS Technology Ltd.",
    "TBOTEK": "TBO Tek Ltd.",
    "TATACHEM": "Tata Chemicals Ltd.",
    "TATACOMM": "Tata Communications Ltd.",
    "TATAELXSI": "Tata Elxsi Ltd.",
    "TATAINVEST": "Tata Investment Corporation Ltd.",
    "TATATECH": "Tata Technologies Ltd.",
    "TTML": "Tata Teleservices (Maharashtra) Ltd.",
    "TECHNOE": "Techno Electric & Engineering Company Ltd.",
    "TEGA": "Tega Industries Ltd.",
    "TEJASNET": "Tejas Networks Ltd.",
    "TENNIND": "Tenneco Clean Air India Ltd.",
    "NIACL": "The New India Assurance Company Ltd.",
    "RAMCOCEM": "The Ramco Cements Ltd.",
    "THERMAX": "Thermax Ltd.",
    "TIMKEN": "Timken India Ltd.",
    "TITAGARH": "Titagarh Rail Systems Ltd.",
    "TORNTPOWER": "Torrent Power Ltd.",
    "TARIL": "Transformers And Rectifiers (India) Ltd.",
    "TRAVELFOOD": "Travel Food Services Ltd.",
    "TRIDENT": "Trident Ltd.",
    "TRITURBINE": "Triveni Turbine Ltd.",
    "TIINDIA": "Tube Investments of India Ltd.",
    "UCOBANK": "UCO Bank",
    "UNOMINDA": "UNO Minda Ltd.",
    "UPL": "UPL Ltd.",
    "UTIAMC": "UTI Asset Management Company Ltd.",
    "UBL": "United Breweries Ltd.",
    "URBANCO": "Urban Company Ltd.",
    "USHAMART": "Usha Martin Ltd.",
    "VTL": "Vardhman Textiles Ltd.",
    "VIJAYA": "Vijaya Diagnostic Centre Ltd.",
    "VMM": "Vishal Mega Mart Ltd.",
    "IDEA": "Vodafone Idea Ltd.",
    "VOLTAS": "Voltas Ltd.",
    "WAAREEENER": "Waaree Energies Ltd.",
    "WELCORP": "Welspun Corp Ltd.",
    "WELSPUNLIV": "Welspun Living Ltd.",
    "WHIRLPOOL": "Whirlpool of India Ltd.",
    "WOCKPHARMA": "Wockhardt Ltd.",
    "YESBANK": "Yes Bank Ltd.",
    "ZFCVINDIA": "ZF Commercial Vehicle Control Systems India Ltd.",
    "ZEEL": "Zee Entertainment Enterprises Ltd.",
    "ZENTEC": "Zen Technologies Ltd.",
    "ZENSARTECH": "Zensar Technolgies Ltd.",
    "ZYDUSWELL": "Zydus Wellness Ltd.",
    "ECLERX": "eClerx Services Ltd.",
    "ASKAUTOLTD": "ASK Automotive Ltd.",
    "AXISCADES": "AXISCADES Technologies Ltd.",
    "AARTIDRUGS": "Aarti Drugs Ltd.",
    "AARTIPHARM": "Aarti Pharmalabs Ltd.",
    "AVL": "Aditya Vision Ltd.",
    "ADVENZYMES": "Advanced Enzyme Tech Ltd.",
    "AEQUS": "Aequs Ltd.",
    "AETHER": "Aether Industries Ltd.",
    "AHLUCONT": "Ahluwalia Contracts (India) Ltd.",
    "AKUMS": "Akums Drugs and Pharmaceuticals Ltd.",
    "APLLTD": "Alembic Pharmaceuticals Ltd.",
    "ALIVUS": "Alivus Life Sciences Ltd.",
    "ALKYLAMINE": "Alkyl Amines Chemicals Ltd.",
    "ALOKINDS": "Alok Industries Ltd.",
    "APOLLO": "Apollo Micro Systems Ltd.",
    "ACI": "Archean Chemical Industries Ltd.",
    "ARVINDFASN": "Arvind Fashions Ltd.",
    "ARVIND": "Arvind Ltd.",
    "ASHAPURMIN": "Ashapura Minechem Ltd.",
    "ASHOKA": "Ashoka Buildcon Ltd.",
    "ASTRAMICRO": "Astra Microwave Products Ltd.",
    "ATLANTAELE": "Atlanta Electricals Ltd.",
    "AURIONPRO": "Aurionpro Solution Ltd.",
    "AVALON": "Avalon Technologies Ltd.",
    "AVANTIFEED": "Avanti Feeds Ltd.",
    "CCAVENUE": "AvenuesAI Ltd.",
    "AWFIS": "Awfis Space Solutions Ltd.",
    "AZAD": "Azad Engineering Ltd.",
    "BAJAJELEC": "Bajaj Electricals Ltd",
    "BALAMINES": "Balaji Amines Ltd.",
    "BALUFORGE": "Balu Forge Industries Ltd.",
    "BANCOINDIA": "Banco Products (India) Ltd.",
    "BIRLACORPN": "Birla Corporation Ltd.",
    "BBOX": "Black Box Ltd.",
    "BLACKBUCK": "Blackbuck Ltd.",
    "BLUESTONE": "BlueStone Jewellery and Lifestyle Ltd.",
    "BORORENEW": "Borosil Renewables Ltd.",
    "CMSINFO": "CMS Info Systems Ltd.",
    "CORONA": "CORONA Remedies Ltd.",
    "CSBBANK": "CSB Bank Ltd.",
    "CAMPUS": "Campus Activewear Ltd.",
    "CRAMC": "Canara Robeco Asset Management Company Ltd.",
    "CAPILLARY": "Capillary Technologies India Ltd.",
    "CELLO": "Cello World Ltd.",
    "CENTURYPLY": "Century Plyboards (India) Ltd.",
    "CERA": "Cera Sanitaryware Ltd",
    "CRIZAC": "Crizac Ltd.",
    "CUPID": "Cupid Ltd.",
    "DCBBANK": "DCB Bank Ltd.",
    "DATAMATICS": "Datamatics Global Services Ltd.",
    "DIACABS": "Diamond Power Infrastructure Ltd.",
    "DBL": "Dilip Buildcon Ltd.",
    "AGARWALEYE": "Dr. Agarwal's Health Care Ltd.",
    "DUMMYINGL1": "Dummy India Glycols ltd. 1",
    "DUMMYINGL2": "Dummy India Glycols ltd. 2",
    "DUMMYINXGN": "Dummy Inox Green Ltd.",
    "DUMMYTRVN": "Dummy Triveni Ltd.",
    "DYNAMATECH": "Dynamatic Technologies Ltd.",
    "EPL": "EPL Ltd.",
    "EDELWEISS": "Edelweiss Financial Services Ltd.",
    "EMIL": "Electronics Mart India Ltd.",
    "ELECTCAST": "Electrosteel Castings Ltd.",
    "ELLEN": "Ellenbarrie Industrial Gases Ltd.",
    "EMBDL": "Embassy Developments Ltd.",
    "ENTERO": "Entero Healthcare Solutions Ltd.",
    "EIEL": "Enviro Infra Engineers Ltd.",
    "EQUITASBNK": "Equitas Small Finance Bank Ltd.",
    "ETHOSLTD": "Ethos Ltd.",
    "EUREKAFORB": "Eureka Forbes Ltd.",
    "FEDFINA": "Fedbank Financial Services Ltd.",
    "FIEMIND": "Fiem Industries Ltd",
    "FINPIPE": "Finolex Industries Ltd.",
    "UTLSOLAR": "Fujiyama Power Systems Ltd.",
    "GHCL": "GHCL Ltd.",
    "GMMPFAUDLR": "GMM Pfaudler Ltd.",
    "GMRP&UI": "GMR Power and Urban Infra Ltd.",
    "GRWRHITECH": "Garware Hi-Tech Films Ltd.",
    "GODREJAGRO": "Godrej Agrovet Ltd.",
    "GOKEX": "Gokaldas Exports Ltd.",
    "GOKULAGRO": "Gokul Agro Resources Ltd.",
    "GREAVESCOT": "Greaves Cotton Ltd.",
    "GRINDWELL": "Grindwell Norton Ltd.",
    "GAEL": "Gujarat Ambuja Exports Ltd.",
    "GNFC": "Gujarat Narmada Valley Fertilizers and Chemicals Ltd.",
    "GPPL": "Gujarat Pipavav Port Ltd.",
    "GSFC": "Gujarat State Fertilizers & Chemicals Ltd.",
    "HGINFRA": "H.G. Infra Engineering Ltd.",
    "HAPPSTMNDS": "Happiest Minds Technologies Ltd.",
    "HCG": "Healthcare Global Enterprises Ltd.",
    "HEMIPROP": "Hemisphere Properties India Ltd.",
    "HERITGFOOD": "Heritage Foods Ltd.",
    "HCC": "Hindustan Construction Co. Ltd.",
    "IFBIND": "IFB Industries Ltd.",
    "IIFLCAPS": "IIFL Capital Services Ltd.",
    "INOXINDIA": "INOX India Ltd.",
    "INDIAGLYCO": "India Glycols Ltd.",
    "INDIASHLTR": "India Shelter Finance Corporation Ltd.",
    "IMFA": "Indian Metals & Ferro Alloys Ltd.",
    "INDIGOPNTS": "Indigo Paints Ltd.",
    "ICIL": "Indo Count Industries Ltd.",
    "INOXGREEN": "Inox Green Energy Services Ltd.",
    "IONEXCHANG": "Ion Exchange (India) Ltd.",
    "JAIBALAJI": "JAI BALAJI INDUSTRIES Ltd.",
    "JKLAKSHMI": "JK Lakshmi Cement Ltd.",
    "JKPAPER": "JK Paper Ltd.",
    "JAMNAAUTO": "Jamna Auto Industries Ltd.",
    "JSFB": "Jana Small Finance Bank Ltd.",
    "JAYNECOIND": "Jayaswal Neco Industries Ltd.",
    "JSLL": "Jeena Sikho Lifecare Ltd.",
    "JLHL": "Jupiter Life Line Hospitals Ltd.",
    "JUSTDIAL": "Justdial Ltd.",
    "JYOTHYLAB": "Jyothy Labs Ltd.",
    "KNRCON": "KNR Constructions Ltd.",
    "KPIGREEN": "KPI Green Energy Ltd.",
    "KRBL": "KRBL Ltd.",
    "KRN": "KRN HEAT EXCHANGER AND REFRIGERATION Ltd.",
    "KSB": "KSB Ltd.",
    "KANSAINER": "Kansai Nerolac Paints Ltd.",
    "KTKBANK": "Karnataka Bank Ltd.",
    "KSCL": "Kaveri Seed Company Ltd.",
    "KIRLOSBROS": "Kirloskar Brothers Ltd.",
    "KIRLPNU": "Kirloskar Pneumatic Company Ltd.",
    "KITEX": "Kitex Garments Ltd.",
    "LXCHEM": "Laxmi Organic Industries Ltd.",
    "IXIGO": "Le Travenues Technology Ltd.",
    "LLOYDSENGG": "Lloyds Engineering Works Ltd.",
    "LLOYDSENT": "Lloyds Enterprises Ltd.",
    "LUMAXTECH": "Lumax Auto Technologies Ltd.",
    "MOIL": "MOIL Ltd.",
    "MSTCLTD": "MSTC Ltd.",
    "MTARTECH": "MTAR Technologies Ltd.",
    "MAHSCOOTER": "Maharashtra Scooters Ltd.",
    "MAHSEAMLES": "Maharashtra Seamless Ltd.",
    "MANORAMA": "Manorama Industries Ltd.",
    "MARKSANS": "Marksans Pharma Ltd.",
    "MASTEK": "Mastek Ltd.",
    "MEDPLUS": "Medplus Health Services Ltd.",
    "METROPOLIS": "Metropolis Healthcare Ltd.",
    "MIDHANI": "Mishra Dhatu Nigam Ltd.",
    "BECTORFOOD": "Mrs. Bectors Food Specialities Ltd.",
    "NEOGEN": "NEOGEN CHEMICALS LTD.",
    "NESCO": "NESCO Ltd.",
    "NFL": "National Fertilizers Ltd.",
    "NAZARA": "Nazara Technologies Ltd.",
    "NETWORK18": "Network18 Media & Investments Ltd.",
    "OPTIEMUS": "Optiemus Infracom Ltd.",
    "ORIENTCEM": "Orient Cement Ltd.",
    "ORKLAINDIA": "Orkla India Ltd.",
    "OSWALPUMPS": "Oswal Pumps Ltd.",
    "PNGJL": "P N Gadgil Jewellers Ltd.",
    "PCJEWELLER": "PC Jeweller Ltd.",
    "PNCINFRA": "PNC Infratech Ltd.",
    "PTC": "PTC India Ltd.",
    "PARAS": "Paras Defence and Space Technologies Ltd.",
    "PARKHOSPS": "Park Medi World Ltd.",
    "PGIL": "Pearl Global Industries Ltd.",
    "PICCADIL": "Piccadily Agro Industries Ltd.",
    "POWERMECH": "Power Mech Projects Ltd.",
    "PRAJIND": "Praj Industries Ltd.",
    "PRICOLLTD": "Pricol Ltd.",
    "PRSMJOHNSN": "Prism Johnson Ltd.",
    "PRIVISCL": "Privi Speciality Chemicals Ltd.",
    "PRUDENT": "Prudent Corporate Advisory Services Ltd.",
    "PURVA": "Puravankara Ltd.",
    "QPOWER": "QUALITY POWER ELECTRICAL EQUIPMENTS Ltd.",
    "QUESS": "Quess Corp Ltd.",
    "RAIN": "Rain Industries Ltd",
    "RALLIS": "Rallis India Ltd.",
    "RCF": "Rashtriya Chemicals & Fertilizers Ltd.",
    "RATEGAIN": "Rategain Travel Technologies Ltd.",
    "RATNAMANI": "Ratnamani Metals & Tubes Ltd.",
    "RTNINDIA": "RattanIndia Enterprises Ltd.",
    "RTNPOWER": "RattanIndia Power Ltd.",
    "RAYMONDLSL": "Raymond Lifestyle Ltd.",
    "REDTAPE": "Redtape Ltd.",
    "REFEX": "Refex Industries Ltd.",
    "RELAXO": "Relaxo Footwears Ltd.",
    "RELIGARE": "Religare Enterprises Ltd.",
    "RBA": "Restaurant Brands Asia Ltd.",
    "ROUTE": "Route Mobile Ltd.",
    "RUBICON": "Rubicon Research Ltd.",
    "SKFINDUS": "SKF India (Industrial) Ltd.",
    "SKFINDIA": "SKF India Ltd.",
    "SKYGOLD": "SKY GOLD AND DIAMONDS Ltd.",
    "SMLMAH": "SML Mahindra Ltd.",
    "SHRIPISTON": "SPR Auto Technologies Ltd.",
    "LOTUSDEV": "SRI LOTUS DEVELOPERS AND REALTY Ltd.",
    "SAATVIKGL": "Saatvik Green Energy Ltd.",
    "SAFARI": "Safari Industries (India) Ltd.",
    "SAMHI": "Samhi Hotels Ltd.",
    "SANDUMA": "Sandur Manganese & Iron Ores Ltd.",
    "SANOFICONR": "Sanofi Consumer Healthcare India Ltd.",
    "SANSERA": "Sansera Engineering Ltd.",
    "SENCO": "Senco Gold Ltd.",
    "STYL": "Seshaasai Technologies Ltd.",
    "SHAILY": "Shaily Engineering Plastics Ltd.",
    "SHAKTIPUMP": "Shakti Pumps (India) Ltd.",
    "SHARDACROP": "Sharda Cropchem Ltd.",
    "SHAREINDIA": "Share India Securities Ltd.",
    "SFL": "Sheela Foam Ltd.",
    "SHILPAMED": "Shilpa Medicare Ltd.",
    "RENUKA": "Shree Renuka Sugars Ltd.",
    "SKIPPER": "Skipper Ltd.",
    "SMARTWORKS": "Smartworks Coworking Spaces Ltd.",
    "SOUTHBANK": "South Indian Bank Ltd.",
    "STARCEMENT": "Star Cement Ltd.",
    "SWSOLAR": "Sterling and Wilson Renewable Energy Ltd.",
    "STLTECH": "Sterlite Technologies Ltd.",
    "STAR": "Strides Pharma Science Ltd.",
    "STYRENIX": "Styrenix Performance Materials Ltd.",
    "SUBROS": "Subros Ltd.",
    "SUDARSCHEM": "Sudarshan Chemical Industries Ltd.",
    "SUDEEPPHRM": "Sudeep Pharma Ltd.",
    "SPARC": "Sun Pharma Advanced Research Company Ltd.",
    "SUNTECK": "Sunteck Realty Ltd.",
    "SUPRIYA": "Supriya Lifescience Ltd.",
    "SURYAROSNI": "Surya Roshni Ltd.",
    "TARC": "TARC Ltd.",
    "TDPOWERSYS": "TD Power Systems Ltd.",
    "TSFINV": "TSF Investments Ltd.",
    "TVSSCS": "TVS Supply Chain Solutions Ltd.",
    "TMB": "Tamilnad Mercantile Bank Ltd.",
    "TANLA": "Tanla Platforms Ltd.",
    "TEXRAIL": "Texmaco Rail & Eng. Ltd.",
    "THANGAMAYL": "Thangamayil Jewellery Ltd.",
    "ANUP": "The Anup Engineering Ltd.",
    "THOMASCOOK": "Thomas Cook (India) Ltd.",
    "THYROCARE": "Thyrocare Technologies Ltd.",
    "TI": "Tilaknagar Industries Ltd.",
    "TIMETECHNO": "Time Technoplast Ltd.",
    "TIPSMUSIC": "Tips Music Ltd.",
    "TRANSRAILL": "Transrail Lighting Ltd.",
    "TRIVENI": "Triveni Engineering & Industries Ltd.",
    "UJJIVANSFB": "Ujjivan Small Finance Bank Ltd.",
    "VGUARD": "V-Guard Industries Ltd.",
    "VMART": "V-Mart Retail Ltd.",
    "VIPIND": "V.I.P. Industries Ltd.",
    "V2RETAIL": "V2 Retail Ltd.",
    "DBREALTY": "VALOR ESTATE Ltd.",
    "WABAG": "Va Tech Wabag Ltd.",
    "VAIBHAVGBL": "Vaibhav Global Ltd.",
    "VARROC": "Varroc Engineering Ltd.",
    "MANYAVAR": "Vedant Fashions Ltd.",
    "VIKRAMSOLR": "Vikram Solar Ltd.",
    "VIYASH": "Viyash Scientific Ltd.",
    "VOLTAMP": "Voltamp Transformers Ltd",
    "WAAREERTL": "Waaree Renewable Technologies Ltd.",
    "WAKEFIT": "Wakefit Innovations Ltd.",
    "WEWORK": "WeWork India Management Ltd.",
    "WEBELSOLAR": "Websol Energy System Ltd.",
    "WELENT": "Welspun Enterprises Ltd.",
    "WESTLIFE": "Westlife Foodworld Ltd.",
    "YATHARTH": "Yatharth Hospital & Trauma Care Services Ltd.",
    "ZAGGLE": "Zaggle Prepaid Ocean Services Ltd.",
    "TATAMOTORS": "Tata Motors Passenger Vehicles Ltd",
    "ZOMATO": "Eternal Ltd (formerly Zomato)"
}

def matches_index_filter(symbol: str, index_filter: Optional[str]) -> bool:
    if not index_filter or index_filter.lower() in ("all", "total_market", "totalmarket", "nifty_total_market", "nifty total market", "indian_market"):
        return True
    
    clean = symbol.strip().upper().replace(".NS", "").replace(".BO", "")
    # Handle aliases
    if clean in ("TATAMOTORS", "TATA_MOTORS"):
        clean = "TMPV"
    elif clean == "ZOMATO":
        clean = "ETERNAL"
        
    f = index_filter.lower().replace(" ", "").replace("_", "").replace("-", "")
    if f in ("nifty50", "50"):
        return clean in NIFTY_50_SYMBOLS
    elif f in ("nifty100", "100"):
        return clean in NIFTY_100_SYMBOLS
    elif f in ("nifty500", "500"):
        return clean in NIFTY_500_SYMBOLS
    elif f in ("midcap100", "niftymidcap100", "midcap"):
        return clean in NIFTY_MIDCAP_100_SYMBOLS
    elif f in ("smallcap100", "niftysmallcap100", "smallcap"):
        return clean in NIFTY_SMALLCAP_100_SYMBOLS
    elif f in ("totalmarket", "niftytotalmarket"):
        return clean in NIFTY_TOTAL_MARKET_SYMBOLS
        
    return True

def get_constituent_company_name(symbol: str) -> Optional[str]:
    clean = symbol.strip().upper().replace(".NS", "").replace(".BO", "")
    return COMPANY_NAMES_MAP.get(clean)
